name: Python application

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # the GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest --cov-report=xml --cov=lib
#    - name: Upload code coverage report to codecov.io
#      uses: codecov/codecov-action@v1
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        flags: unittests
#    - name: Upload code coverage report to coveralls.io
#      env:
#        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#      run: coveralls --verbose
    - name: Publish code coverage score as pr comment
      if: github.event.pull_request
      uses: thollander/actions-comment-pull-request@1.0.0
      with:
        message: 'Dynamic message : your current branch is ${{ github.head_ref }}. Check [Contexts and expression syntax](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions) available variables.'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
