name: Python application

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # the GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest --cov-report=xml --cov=lib
#    - name: Upload code coverage report to codecov.io
#      uses: codecov/codecov-action@v1
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        flags: unittests
#    - name: Upload code coverage report to coveralls.io
#      env:
#        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#      run: coveralls --verbose
    - name: Extract code coverage info
      id: extract_coverage
      shell: bash
      run: |
        sudo apt-get install libxml-xpath-perl
        coverage_percentage=$(bc <<< "`xpath -e /coverage/@line-rate coverage.xml | sed -n -e 's/^.*line-rate=//p' | sed -n -e 's/\"//gp'`*100")
        echo ::set-output name=coverage_percentage::$coverage_percentage
    - name: Publish code coverage score as pr comment
      if: github.event.pull_request
      uses: thollander/actions-comment-pull-request@1.0.0
      with:
        message: 'Code coverage: ${{ steps.extract_coverage.outputs.coverage_percentage }}%.'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
